services:
  stepfunctions-local:
    image: amazon/aws-stepfunctions-local
    container_name: stepfunctions-local
    ports:
      - "8083:8083"
    volumes:
      - type: bind
        source: ./MockConfigFile.json
        target: /home/StepFunctionsLocal/MockConfigFile.json
        read_only: true
    environment:
      SFN_MOCK_CONFIG: "/home/StepFunctionsLocal/MockConfigFile.json"
    env_file:
      - aws-stepfunctions-local-credentials.txt
    networks:
      - sam-app-network
      
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "./data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - sam-app-network

  dynamodb-admin: 
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
    networks:
      - sam-app-network

  localstack-local:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-local}"
    image: localstack/localstack
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - sam-app-network
    
networks:
  sam-app-network:
    name: sam-app-network
  